export type FeatureStatus = 'live' | 'admin' | 'planned'
export type FeatureDefinition = { id: string; label: string; category: string; status: FeatureStatus }

type FeatureTuple = readonly [string, string, string, FeatureStatus]

export const FEATURE_REGISTRY: FeatureTuple[] = [
  // Account and navigation
  ['login-back-home', 'Login Back ও Home navigation', 'অ্যাকাউন্ট', 'live'], ['google-mobile-login', 'Mobile Google login fallback', 'অ্যাকাউন্ট', 'live'], ['account-hub', 'Account quick-action hub', 'অ্যাকাউন্ট', 'live'], ['profile-photo', 'Profile photo upload', 'অ্যাকাউন্ট', 'live'], ['email-verification', 'Email verification control', 'অ্যাকাউন্ট', 'live'], ['password-change', 'Password change', 'অ্যাকাউন্ট', 'live'], ['recent-searches', 'Recent search memory', 'অ্যাকাউন্ট', 'live'], ['saved-searches', 'Saved search library', 'অ্যাকাউন্ট', 'live'], ['wishlist-folders', 'Wishlist folders', 'অ্যাকাউন্ট', 'live'],
  // Discovery, sharing and product trust
  ['advanced-filters', 'Advanced price/category/location filters', 'ডিসকভারি', 'live'], ['sort-newest', 'Newest sorting', 'ডিসকভারি', 'live'], ['sort-oldest', 'Oldest sorting', 'ডিসকভারি', 'live'], ['sort-popular', 'Popular sorting', 'ডিসকভারি', 'live'], ['sort-discount', 'Discount sorting', 'ডিসকভারি', 'live'], ['grid-list-view', 'Grid/list product view', 'ডিসকভারি', 'live'], ['compare-products', 'Product comparison', 'ডিসকভারি', 'live'], ['product-share-preview', 'First-image social share preview', 'ডিসকভারি', 'live'], ['recently-viewed', 'Recently viewed products', 'ডিসকভারি', 'live'], ['related-products', 'Related product recommendations', 'ডিসকভারি', 'live'],
  // Buyer trust and engagement
  ['price-alert', 'Price-drop alert', 'বিশ্বাস', 'live'], ['stock-alert', 'Back-in-stock alert', 'বিশ্বাস', 'live'], ['seller-follow', 'Seller follow', 'বিশ্বাস', 'live'], ['product-questions', 'Product Q&A', 'বিশ্বাস', 'live'], ['product-report', 'Product report', 'বিশ্বাস', 'live'], ['verified-seller', 'Verified seller badge', 'বিশ্বাস', 'live'], ['delivery-badges', 'COD/free/fast/return badges', 'বিশ্বাস', 'live'], ['escrow-protection', 'Escrow protection messaging', 'বিশ্বাস', 'live'], ['review-moderation', 'Review moderation', 'বিশ্বাস', 'admin'], ['verified-purchase', 'Verified-purchase review label', 'বিশ্বাস', 'planned'],
  // Checkout and payments
  ['order-summary', 'BDT order summary', 'চেকআউট', 'live'], ['coupon-validation', 'Coupon validation', 'চেকআউট', 'live'], ['return-policy-ack', 'Return policy acknowledgement', 'চেকআউট', 'live'], ['digital-delivery', 'Digital delivery', 'চেকআউট', 'live'], ['payment-callback', 'Payment callback recovery', 'চেকআউট', 'live'], ['payment-retry', 'Pending payment retry', 'চেকআউট', 'live'], ['invoice-receipt', 'Invoice/receipt view', 'চেকআউট', 'live'], ['shipping-cost-estimate', 'Shipping cost estimate', 'চেকআউট', 'planned'], ['gift-message', 'Gift message at checkout', 'চেকআউট', 'planned'],
  // Orders, return and safety
  ['order-search', 'Order search', 'অর্ডার', 'live'], ['order-status-filter', 'Order status filter', 'অর্ডার', 'live'], ['order-timeline', 'Order status timeline', 'অর্ডার', 'live'], ['delivery-confirm', 'Buyer delivery confirmation', 'অর্ডার', 'live'], ['seller-shipping-action', 'Seller ship action', 'অর্ডার', 'live'], ['cancellation-request', 'Cancellation request', 'অর্ডার', 'live'], ['dispute-report', 'Dispute report', 'অর্ডার', 'live'], ['dispute-messages', 'Dispute message thread', 'অর্ডার', 'live'], ['return-refund-policy', 'Return/refund policy page', 'অর্ডার', 'admin'], ['order-csv-export', 'Order export', 'অর্ডার', 'planned'],
  // Seller operations
  ['seller-onboarding', 'Seller onboarding checklist', 'সেলার', 'live'], ['seller-verification', 'Seller verification', 'সেলার', 'live'], ['listing-quality-score', 'Listing quality score', 'সেলার', 'live'], ['delivery-settings', 'Listing delivery settings', 'সেলার', 'live'], ['seller-dashboard', 'Seller dashboard', 'সেলার', 'live'], ['seller-conversion-rate', 'Seller conversion rate', 'সেলার', 'live'], ['seller-average-sale', 'Average sale metric', 'সেলার', 'live'], ['seller-report-export', 'Seller performance export', 'সেলার', 'live'], ['seller-drafts', 'Seller drafts', 'সেলার', 'live'], ['duplicate-listing', 'Duplicate listing', 'সেলার', 'live'], ['bulk-price-update', 'Bulk price update', 'সেলার', 'planned'], ['bulk-image-upload', 'Bulk image upload', 'সেলার', 'planned'], ['vacation-mode', 'Vacation mode', 'সেলার', 'planned'], ['payout-history', 'Payout history', 'সেলার', 'admin'], ['seller-chat-filters', 'Seller chat filters', 'সেলার', 'planned'],
  // Chat, help and AI
  ['buyer-seller-chat', 'Buyer/seller chat', 'সাপোর্ট', 'live'], ['chat-race-safe', 'Race-safe chat thread creation', 'সাপোর্ট', 'live'], ['chat-realtime', 'Realtime chat refresh', 'সাপোর্ট', 'live'], ['chat-unread-count', 'Chat unread count', 'সাপোর্ট', 'live'], ['chat-product-card', 'Product recommendation in chat', 'সাপোর্ট', 'planned'], ['help-center', 'Central Help Center', 'সাপোর্ট', 'live'], ['faq-page', 'FAQ page', 'সাপোর্ট', 'admin'], ['user-education-hub', 'User Education Hub', 'সাপোর্ট', 'admin'], ['seller-education-hub', 'Seller Education Hub', 'সাপোর্ট', 'admin'], ['ai-help-assistant', 'Agent Router AI Help', 'সাপোর্ট', 'admin'],
  // Rewards and retention
  ['daily-checkin', 'Server-backed daily check-in', 'রিওয়ার্ড', 'live'], ['checkin-streak', 'Check-in streak', 'রিওয়ার্ড', 'live'], ['reward-coins', 'Reward coin balance', 'রিওয়ার্ড', 'live'], ['vip-status', 'VIP status display', 'রিওয়ার্ড', 'live'], ['free-shipping-banner', 'Free shipping messaging', 'রিওয়ার্ড', 'live'], ['notification-center', 'Notification center', 'রিওয়ার্ড', 'live'], ['notification-filter', 'Notification filter', 'রিওয়ার্ড', 'live'], ['mark-all-read', 'Mark all notifications read', 'রিওয়ার্ড', 'live'], ['seller-follow-reward', 'Seller follow reward', 'রিওয়ার্ড', 'planned'], ['referral-program', 'Referral program', 'রিওয়ার্ড', 'planned'],
  // Admin and control
  ['admin-dashboard', 'Admin dashboard', 'অ্যাডমিন', 'admin'], ['admin-orders', 'Admin order control', 'অ্যাডমিন', 'admin'], ['admin-products', 'Admin product control', 'অ্যাডমিন', 'admin'], ['admin-categories', 'Admin category control', 'অ্যাডমিন', 'admin'], ['admin-sellers', 'Admin seller verification', 'অ্যাডমিন', 'admin'], ['admin-customers', 'Admin customer list', 'অ্যাডমিন', 'admin'], ['admin-payouts', 'Admin payout review', 'অ্যাডমিন', 'admin'], ['admin-disputes', 'Admin dispute resolution', 'অ্যাডমিন', 'admin'], ['admin-reviews', 'Admin review moderation', 'অ্যাডমিন', 'admin'], ['admin-coupons', 'Admin coupon control', 'অ্যাডমিন', 'admin'], ['admin-banners', 'Admin banner control', 'অ্যাডমিন', 'admin'], ['admin-public-pages', 'Admin public pages editor', 'অ্যাডমিন', 'admin'], ['admin-site-settings', 'Admin site settings', 'অ্যাডমিন', 'admin'], ['admin-feature-flags', 'Admin feature flags', 'অ্যাডমিন', 'admin'], ['admin-audit-log', 'Admin audit log', 'অ্যাডমিন', 'admin'],
]

export const FEATURE_DEFINITIONS: FeatureDefinition[] = FEATURE_REGISTRY.map(([id, label, category, status]) => ({ id, label, category, status }))
