import { ArrowRight, BadgeCheck, BookOpen, Check, ChevronDown, ChevronRight, CircleAlert, Gamepad2, Headphones, KeyRound, LockKeyhole, MessageCircle, PackageCheck, Palette, Search, ShieldCheck, Sparkles, Store, Users, WalletCards } from 'lucide-react'
import { useState } from 'react'
import { Helmet } from 'react-helmet-async'

const categories = [
  { href: '/app/products?q=game', label: 'গেম ও গেমিং', detail: 'Game ID, keys ও gaming access', icon: Gamepad2, tone: 'bg-violet-50 text-violet-700' },
  { href: '/app/products?q=software', label: 'সফটওয়্যার', detail: 'Tools, license ও digital utility', icon: Search, tone: 'bg-sky-50 text-sky-700' },
  { href: '/app/products?q=subscription', label: 'সাবস্ক্রিপশন', detail: 'Premium apps ও memberships', icon: Sparkles, tone: 'bg-amber-50 text-amber-700' },
  { href: '/app/products?q=course', label: 'কোর্স ও শিক্ষা', detail: 'শেখা, ebook ও skill resources', icon: BookOpen, tone: 'bg-emerald-50 text-emerald-700' },
  { href: '/app/products?q=design', label: 'ডিজাইন ও টেমপ্লেট', detail: 'Creative assets ও templates', icon: Palette, tone: 'bg-rose-50 text-rose-700' },
  { href: '/app/products?q=service', label: 'ডিজিটাল সেবা', detail: 'Online service ও support', icon: Headphones, tone: 'bg-orange-50 text-orange-700' },
]

const faqItems = [
  { question: 'BikriKoro-তে কেনাকাটা কীভাবে নিরাপদ?', answer: 'প্রতিটি listing-এর seller profile, rating, delivery mode ও product details দেখে অর্ডার করুন। অর্ডারের status ও delivery তথ্য account-এর ভিতরে পরিষ্কারভাবে দেখা যায়।' },
  { question: 'ডিজিটাল product কীভাবে delivery হয়?', answer: 'Product অনুযায়ী secure automatic delivery অথবা seller-এর manual delivery হতে পারে। Automatic delivery-র secret তথ্য encrypted অবস্থায় সংরক্ষিত থাকে।' },
  { question: 'আমি কি seller হিসেবে product বিক্রি করতে পারব?', answer: 'অবশ্যই। Seller onboarding সম্পন্ন করে listing তৈরি করুন, delivery method বেছে নিন এবং আপনার digital product-এর জন্য buyer-এর কাছে পৌঁছান।' },
  { question: 'সমস্যা হলে কীভাবে সাহায্য পাব?', answer: 'Order, payment, account বা complaint-এর জন্য Help Center ব্যবহার করুন। প্রয়োজনে একটি support case খুলে আমাদের team-এর সাথে যোগাযোগ করতে পারবেন।' },
]

export default function MarketingLanding() {
  return <div className="site-minimal min-h-screen overflow-x-hidden bg-[#f7fbfa] text-ink-900">
    <Helmet>
      <title>BikriKoro — বাংলাদেশের নিরাপদ ডিজিটাল প্রোডাক্ট মার্কেটপ্লেস</title>
      <meta name="description" content="BikriKoro-তে নিরাপদে ডিজিটাল প্রোডাক্ট কিনুন ও বিক্রি করুন। বিভিন্ন ডিজিটাল প্রোডাক্ট আবিষ্কার করুন, নিজের প্রোডাক্ট লিস্ট করুন এবং সহজ ও নিরাপদ marketplace experience উপভোগ করুন।" />
      <meta name="keywords" content="digital marketplace Bangladesh, game account কেনাবেচা, software subscription, digital service, BikriKoro" />
      <link rel="canonical" href="https://www.bikrikoro.com/" />
      <script type="application/ld+json">{JSON.stringify({ '@context': 'https://schema.org', '@type': 'WebPage', name: 'BikriKoro — বাংলাদেশের নিরাপদ Digital Marketplace', url: 'https://www.bikrikoro.com/', description: 'বাংলাদেশের নিরাপদ digital marketplace যেখানে game, software, subscription, course ও digital service কেনাবেচা করা যায়।', about: ['digital marketplace', 'secure digital delivery', 'online selling in Bangladesh'] })}</script>
    </Helmet>

    <header className="sticky top-0 z-30 border-b border-brand-100/70 bg-white/90 px-4 py-3 backdrop-blur-xl sm:px-6"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><a href="/" className="flex min-w-0 items-center gap-2.5" aria-label="BikriKoro home"><img src="/icon-512.png" alt="BikriKoro logo" className="h-9 w-9 shrink-0 rounded-xl shadow-sm" /><span className="truncate text-lg font-black tracking-tight sm:text-xl">BikriKoro<span className="text-brand-600">.Com</span></span></a><nav className="hidden items-center gap-6 text-sm font-semibold text-ink-600 md:flex" aria-label="প্রধান নেভিগেশন"><a href="#how-it-works" className="transition hover:text-brand-700">কীভাবে কাজ করে</a><a href="#categories" className="transition hover:text-brand-700">ক্যাটাগরি</a><a href="#sellers" className="transition hover:text-brand-700">সেলার</a><a href="/about" className="transition hover:text-brand-700">আমাদের সম্পর্কে</a><a href="/help" className="transition hover:text-brand-700">সাপোর্ট</a></nav><a href="/app" className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-brand-600 px-3.5 py-2.5 text-sm font-extrabold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-brand-700 sm:px-4">Marketplace খুলুন <ArrowRight size={16} /></a></div></header>

    <main>
      <section className="relative isolate overflow-hidden px-4 pb-14 pt-12 sm:px-6 sm:pb-20 sm:pt-20"><div className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[38rem] bg-[radial-gradient(circle_at_75%_15%,rgba(200,229,233,0.75),transparent_40%),radial-gradient(circle_at_12%_22%,rgba(255,240,230,0.9),transparent_34%)]" /><div className="mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-[.92fr_1.08fr] lg:gap-16"><div className="min-w-0"><span className="inline-flex max-w-full items-center gap-2 rounded-full border border-brand-200 bg-white px-3 py-1.5 text-xs font-bold text-brand-700 shadow-sm"><ShieldCheck size={14} className="shrink-0" /> বাংলাদেশের নিরাপদ digital marketplace</span><h1 className="mt-5 max-w-2xl text-[clamp(2.25rem,6vw,4.75rem)] font-black leading-[1.1] tracking-[-0.045em] text-ink-900">ডিজিটাল product কিনুন, <span className="text-brand-600">ভয় ছাড়াই।</span></h1><p className="mt-5 max-w-xl text-base leading-8 text-ink-600 sm:text-lg">Game, software, subscription, course ও digital service—স্বচ্ছ seller profile, secure delivery এবং support-সহ এক জায়গায়।</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="/app" className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand-600 px-6 py-3.5 text-base font-extrabold text-white shadow-lg shadow-brand-600/20 transition hover:-translate-y-0.5 hover:bg-brand-700">প্রোডাক্ট ব্রাউজ করুন <ArrowRight size={18} /></a><a href="/become-seller" className="inline-flex items-center justify-center gap-2 rounded-xl border border-brand-200 bg-white px-6 py-3.5 text-base font-bold text-brand-700 transition hover:-translate-y-0.5 hover:bg-brand-50"><Store size={18} /> সেলার হোন</a></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-3 text-sm font-semibold text-ink-600"><span className="inline-flex items-center gap-2"><LockKeyhole size={16} className="text-brand-600" /> Secure delivery</span><span className="inline-flex items-center gap-2"><BadgeCheck size={16} className="text-brand-600" /> Seller profile</span><span className="inline-flex items-center gap-2"><MessageCircle size={16} className="text-brand-600" /> Human support</span></div></div><TrustExchangeVisual /></div></section>

      <section className="border-y border-outline bg-[#10281f] px-4 py-8 text-white sm:px-6"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-5 sm:grid-cols-4 sm:gap-8"><Metric value="6+" label="Digital categories" /><Metric value="24/7" label="Marketplace access" /><Metric value="100%" label="Order visibility" /><Metric value="1 place" label="Buy & sell securely" /></div></section>

      <section id="how-it-works" className="px-4 py-16 sm:px-6 sm:py-20"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="text-sm font-bold text-brand-700">A clear path to every deal</p><h2 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">লেনদেনের মাঝখানে থাকুক স্বচ্ছতা</h2><p className="mt-3 text-sm leading-7 text-ink-500">BikriKoro buyer ও seller—দুজনের জন্যই order, delivery এবং support-কে সহজভাবে সাজায়।</p></div><div className="mt-10 grid gap-4 md:grid-cols-4"><Process number="01" icon={Search} title="পণ্য খুঁজুন" detail="Category, search ও seller profile দেখে বেছে নিন।" /><Process number="02" icon={WalletCards} title="অর্ডার করুন" detail="Product details দেখে পরিষ্কার flow-এ order সম্পন্ন করুন।" /><Process number="03" icon={KeyRound} title="ডেলিভারি পান" detail="Automatic বা manual delivery status account-এ দেখুন।" /><Process number="04" icon={PackageCheck} title="নিশ্চিত করুন" detail="পণ্য পেয়ে review দিন এবং প্রয়োজনে support নিন।" /></div></div></section>

      <section id="categories" className="border-y border-outline bg-white px-4 py-16 sm:px-6 sm:py-20"><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-brand-700">Marketplace</p><h2 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">আপনার প্রয়োজনের digital category</h2><p className="mt-2 max-w-xl text-sm leading-6 text-ink-500">একটি category বেছে নিয়ে সরাসরি marketplace-এ product দেখুন।</p></div><a href="/app/products" className="inline-flex items-center gap-1 text-sm font-bold text-brand-700 hover:underline">সব products দেখুন <ArrowRight size={15} /></a></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{categories.map(({ href, label, detail, icon: Icon, tone }) => <a key={href} href={href} className="group flex min-w-0 items-center gap-4 rounded-2xl border border-outline bg-[#fbfefc] p-4 shadow-[0_8px_24px_rgba(23,33,29,0.03)] transition hover:-translate-y-1 hover:border-brand-300 hover:shadow-lg"><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-xl ${tone}`}><Icon size={23} /></span><span className="min-w-0 flex-1"><span className="block font-extrabold text-ink-900">{label}</span><span className="mt-1 block text-xs leading-5 text-ink-500">{detail}</span></span><ChevronRight size={17} className="shrink-0 text-ink-300 transition group-hover:translate-x-1 group-hover:text-brand-600" /></a>)}</div></div></section>

      <section className="px-4 py-16 sm:px-6 sm:py-20"><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold text-brand-700">Neutral protection</p><h2 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">সমস্যা হলে আপনি একা নন</h2><p className="mt-4 text-sm leading-7 text-ink-600">কোনো order বা delivery নিয়ে প্রশ্ন থাকলে evidence-সহ support case খুলতে পারবেন। আমাদের লক্ষ্য হলো buyer ও seller—দুই পক্ষের তথ্য শুনে পরিষ্কারভাবে সমাধান করা।</p><a href="/help" className="mt-6 inline-flex items-center gap-2 font-bold text-brand-700 hover:underline">সাপোর্ট কীভাবে কাজ করে দেখুন <ArrowRight size={16} /></a></div><div className="grid gap-3 sm:grid-cols-3"><Protection icon={MessageCircle} title="শুনুন" detail="আপনার সমস্যা ও context জানান" /><Protection icon={CircleAlert} title="পর্যালোচনা" detail="Order ও evidence দেখে সিদ্ধান্ত" /><Protection icon={ShieldCheck} title="সমাধান" detail="পরবর্তী পদক্ষেপ পরিষ্কারভাবে জানান" /></div></div></section>

      <section id="sellers" className="border-y border-outline bg-[#eaf5f1] px-4 py-16 sm:px-6 sm:py-20"><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-sm font-bold text-brand-700">For sellers</p><h2 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">আপনার digital storefront, আপনার নিয়ন্ত্রণে</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-ink-600">একবার listing তৈরি করে buyer-এর কাছে পৌঁছান। Secure delivery, draft saving এবং seller dashboard আপনার কাজকে আরও সহজ করে।</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><Benefit title="সহজ listing" detail="ধাপে ধাপে product publish করুন" /><Benefit title="Automatic delivery" detail="অফলাইনে থাকলেও delivery flow চালু রাখুন" /><Benefit title="Seller profile" detail="বিশ্বাস তৈরি করুন rating ও history দিয়ে" /><Benefit title="Clear earnings" detail="Order ও payout status এক জায়গায় দেখুন" /></div><a href="/become-seller" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-brand-600 px-5 py-3 font-extrabold text-white transition hover:bg-brand-700">সেলার হিসেবে শুরু করুন <ArrowRight size={17} /></a></div><div className="rounded-3xl border border-brand-100 bg-white p-5 shadow-[0_20px_60px_rgba(6,104,117,0.12)] sm:p-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-600">Seller promise</p><p className="mt-4 text-2xl font-black leading-tight text-ink-900">List once.<br /><span className="text-brand-600">Deliver with confidence.</span></p><div className="mt-7 space-y-3"><div className="flex items-center gap-3 rounded-xl bg-brand-50 p-3"><Check size={18} className="text-brand-600" /><span className="text-sm font-bold text-ink-800">Encrypted digital delivery</span></div><div className="flex items-center gap-3 rounded-xl bg-brand-50 p-3"><Check size={18} className="text-brand-600" /><span className="text-sm font-bold text-ink-800">Resumable listing drafts</span></div><div className="flex items-center gap-3 rounded-xl bg-brand-50 p-3"><Check size={18} className="text-brand-600" /><span className="text-sm font-bold text-ink-800">Buyer ও seller support</span></div></div></div></div></section>

      <section className="px-4 py-16 sm:px-6 sm:py-20"><div className="mx-auto max-w-3xl"><div className="text-center"><p className="text-sm font-bold text-brand-700">FAQ</p><h2 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">প্রশ্ন আছে? উত্তর আছে।</h2><p className="mt-3 text-sm leading-6 text-ink-500">Marketplace, security ও selling নিয়ে সাধারণ প্রশ্নগুলোর উত্তর।</p></div><div className="mt-8 space-y-3">{faqItems.map((item) => <FaqItem key={item.question} {...item} />)}</div></div></section>

      <section className="bg-[#10281f] px-4 py-14 text-white sm:px-6 sm:py-18"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-6 sm:flex-row sm:items-center"><div><p className="text-sm font-bold text-brand-100">Your next safe deal starts here</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">কেনা-বেচা হোক বিশ্বাসের সাথে</h2><p className="mt-2 max-w-xl text-sm leading-6 text-white/70">Marketplace-এ প্রবেশ করুন অথবা আপনার প্রথম digital listing তৈরি করুন।</p></div><div className="flex flex-col gap-3 sm:flex-row"><a href="/app" className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand-500 px-6 py-3.5 text-sm font-extrabold text-white transition hover:bg-brand-400">Marketplace খুলুন <ArrowRight size={17} /></a><a href="/help" className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/20 px-6 py-3.5 text-sm font-bold text-white transition hover:bg-white/10">সাহায্য নিন</a></div></div></section>
    </main>

    <footer className="border-t border-outline bg-white px-4 py-8 sm:px-6"><div className="mx-auto flex max-w-6xl flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black text-ink-900">BikriKoro<span className="text-brand-600">.Com</span></p><p className="mt-1 text-xs text-ink-500">বাংলাদেশের নিরাপদ digital marketplace</p></div><nav className="flex flex-wrap gap-x-5 gap-y-2 text-sm font-semibold text-ink-600" aria-label="Footer navigation"><a href="/about" className="hover:text-brand-700">About</a><a href="/help" className="hover:text-brand-700">Support</a><a href="/faq" className="hover:text-brand-700">FAQ</a><a href="/privacy" className="hover:text-brand-700">Privacy</a><a href="/app" className="font-bold text-brand-700 hover:underline">Open marketplace</a></nav></div></footer>
  </div>
}

function TrustExchangeVisual() {
  return <div className="trust-visual relative mx-auto w-full max-w-[34rem]" aria-label="ক্রেতা ও seller-এর নিরাপদ digital exchange" role="img"><div className="trust-visual-grid absolute inset-0 rounded-[2rem]" /><div className="relative min-h-[27rem] overflow-hidden rounded-[2rem] border border-brand-100 bg-white/80 p-4 shadow-[0_28px_80px_rgba(6,104,117,0.16)] backdrop-blur sm:min-h-[31rem] sm:p-6"><div className="flex items-center justify-between"><span className="inline-flex items-center gap-2 rounded-full bg-brand-50 px-3 py-1.5 text-xs font-extrabold text-brand-700"><ShieldCheck size={14} /> Secure exchange</span><span className="text-xs font-bold text-ink-400">BikriKoro flow</span></div><div className="trust-orbit" aria-hidden="true" /><div className="trust-orbit trust-orbit-two" aria-hidden="true" /><div className="trust-person trust-seller"><span className="trust-avatar bg-[#fff0e6] text-accent-600"><Store size={22} /></span><span><strong>Seller</strong><small>পণ্য পাঠাচ্ছেন</small></span></div><div className="trust-person trust-buyer"><span className="trust-avatar bg-brand-100 text-brand-700"><Users size={22} /></span><span><strong>Customer</strong><small>নিরাপদে গ্রহণ করছেন</small></span></div><div className="trust-center"><span className="trust-shield"><ShieldCheck size={29} /></span><strong>Protected</strong><small>স্বচ্ছ লেনদেন</small></div><div className="trust-package trust-package-one"><KeyRound size={15} /> Digital key</div><div className="trust-package trust-package-two"><PackageCheck size={15} /> Delivery ready</div><div className="absolute inset-x-4 bottom-4 rounded-2xl border border-brand-100 bg-white p-4 shadow-lg sm:inset-x-6 sm:bottom-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-brand-600 text-white"><LockKeyhole size={19} /></span><div className="min-w-0 flex-1"><p className="text-sm font-extrabold text-ink-900">তথ্য সুরক্ষিত আছে</p><p className="mt-0.5 text-xs leading-5 text-ink-500">Seller ও customer—দুজনের জন্য পরিষ্কার delivery flow</p></div><Check size={19} className="shrink-0 text-brand-600" /></div></div></div></div>
}

function Metric({ value, label }: { value: string; label: string }) { return <div className="text-center sm:text-left"><p className="text-2xl font-black sm:text-3xl">{value}</p><p className="mt-1 text-xs text-white/60 sm:text-sm">{label}</p></div> }
function Process({ number, icon: Icon, title, detail }: { number: string; icon: typeof Search; title: string; detail: string }) { return <article className="rounded-2xl border border-outline bg-white p-5 shadow-[0_8px_24px_rgba(23,33,29,0.04)] transition hover:-translate-y-1 hover:shadow-md"><div className="flex items-center justify-between"><span className="text-sm font-black text-brand-600">{number}</span><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-100 text-brand-700"><Icon size={19} /></span></div><h3 className="mt-5 font-extrabold text-ink-900">{title}</h3><p className="mt-2 text-sm leading-6 text-ink-600">{detail}</p></article> }
function Protection({ icon: Icon, title, detail }: { icon: typeof MessageCircle; title: string; detail: string }) { return <div className="rounded-2xl border border-outline bg-white p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-100 text-brand-700"><Icon size={19} /></span><h3 className="mt-4 font-extrabold text-ink-900">{title}</h3><p className="mt-1 text-sm leading-6 text-ink-500">{detail}</p></div> }
function Benefit({ title, detail }: { title: string; detail: string }) { return <div className="flex gap-2.5"><Check size={18} className="mt-0.5 shrink-0 text-brand-600" /><div><p className="text-sm font-extrabold text-ink-900">{title}</p><p className="mt-0.5 text-xs leading-5 text-ink-600">{detail}</p></div></div> }
function FaqItem({ question, answer }: { question: string; answer: string }) { const [open, setOpen] = useState(false); return <div className="rounded-2xl border border-outline bg-white"><button type="button" onClick={() => setOpen((value) => !value)} className="flex w-full items-center gap-4 p-4 text-left font-extrabold text-ink-900 sm:p-5" aria-expanded={open}><span className="min-w-0 flex-1">{question}</span><ChevronDown size={18} className={`shrink-0 text-brand-600 transition ${open ? 'rotate-180' : ''}`} /></button>{open && <p className="border-t border-outline px-4 pb-5 pt-3 text-sm leading-7 text-ink-600 sm:px-5">{answer}</p>}</div> }
