import { CircleHelp, FileText, Headphones, Info, LockKeyhole, MessagesSquare, RefreshCcw, School, Settings2, ShieldCheck, Sparkles, Store } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Helmet } from 'react-helmet-async'
import { Layout } from '@/components/Layout'
import { replayWelcomeSplash } from '@/lib/welcomeSplash'

const groups = [
  { title: 'সহায়তা', items: [['/help', 'সহায়তা কেন্দ্র', 'কেনাকাটা, পেমেন্ট, ডেলিভারি ও অ্যাকাউন্ট সহায়তা', CircleHelp], ['/faq', 'সাধারণ প্রশ্ন', 'দ্রুত FAQ উত্তর দেখুন', MessagesSquare], ['/contact', 'যোগাযোগ ও সাপোর্ট', 'অর্ডার বা অ্যাকাউন্টের সমস্যায় জানান', Headphones]] },
  { title: 'নিরাপত্তা ও নীতি', items: [['/privacy', 'গোপনীয়তা নীতি', 'তথ্য সংগ্রহ ও নিরাপত্তা', LockKeyhole], ['/return-policy', 'ফেরত ও অর্থ ফেরত', 'পণ্য না মিললে করণীয়', RefreshCcw], ['/terms', 'ব্যবহারের শর্ত', 'বাজার ব্যবহারের নিয়ম', FileText]] },
  { title: 'শিখুন', items: [['/user-education', 'ক্রেতা শিক্ষা', 'নিরাপদে কেনাকাটার গাইড', School], ['/seller-education', 'বিক্রেতা শিক্ষা', 'ভালো তালিকা তৈরি ও বিক্রির গাইড', Store], ['/about', 'আমাদের সম্পর্কে', 'BikriKoro-এর উদ্দেশ্য', Info]] },
]

export default function SettingsHub() {
  return <Layout wide><Helmet><title>সেটিংস ও সহায়তা কেন্দ্র | BikriKoro.Com</title></Helmet><div className="mx-auto max-w-5xl"><div className="rounded-3xl bg-ink-900 p-6 text-white sm:p-8"><div className="flex items-start justify-between gap-4"><div><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-brand-500"><Settings2 size={22} /></div><h1 className="mt-4 text-2xl font-bold">সেটিংস ও সহায়তা কেন্দ্র</h1><p className="mt-2 max-w-xl text-sm leading-6 text-white/70">আপনার অ্যাকাউন্ট, নিরাপত্তা, সহায়তা, নীতি ও বাজার-শিক্ষা—সব এক জায়গায়।</p></div><ShieldCheck className="text-brand-300" size={28} /></div></div><section className="mt-5 flex flex-col items-start justify-between gap-3 rounded-2xl border border-brand-200 bg-brand-50 p-4 sm:flex-row sm:items-center"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-500 text-white"><Sparkles size={18} /></span><div><h2 className="font-bold text-ink-900">BikriKoro পরিচিতি আবার দেখুন</h2><p className="mt-1 text-xs leading-5 text-ink-600">আমাদের নিরাপদ কেনাকাটা, বিক্রেতা ও নোটিফিকেশন সেবা সম্পর্কে সংক্ষিপ্ত গাইড দেখুন।</p></div></div><button type="button" onClick={replayWelcomeSplash} className="shrink-0 rounded-xl bg-brand-500 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-brand-600">স্বাগত স্ক্রিন দেখুন</button></section><div className="mt-6 space-y-7">{groups.map((group) => <section key={group.title}><h2 className="mb-3 text-sm font-bold uppercase tracking-wide text-ink-500">{group.title}</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{group.items.map(([to, label, description, Icon]) => <Link key={to as string} to={to as string} className="group rounded-2xl border border-outline bg-surface p-4 transition hover:-translate-y-0.5 hover:border-brand-500 hover:shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50 text-brand-700"><Icon size={19} /></span><span className="min-w-0 flex-1"><span className="block font-semibold text-ink-900">{label as string}</span><span className="mt-1 block text-xs leading-5 text-ink-500">{description as string}</span></span><span className="text-lg text-ink-300 transition group-hover:translate-x-0.5 group-hover:text-brand-600">›</span></div></Link>)}</div></section>)}</div></div></Layout>
}
