import { CheckCircle2, FileCheck2, QrCode, ScanFace, ShieldCheck } from 'lucide-react'

function GuideShell({ label, children }: { label: string; children: React.ReactNode }) {
  return <div className="w-full max-w-[340px] overflow-hidden rounded-xl border border-brand-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-brand-100 bg-brand-50 px-3 py-1.5"><span className="text-[10px] font-extrabold tracking-[0.1em] text-brand-800">{label}</span><span className="rounded-full bg-amber-100 px-2 py-0.5 text-[9px] font-bold text-amber-900">নমুনা</span></div>{children}</div>
}

export function NidGuideCard({ side }: { side: 'front' | 'back' }) {
  const isFront = side === 'front'
  return <GuideShell label={`পরিচয়পত্রের ${isFront ? 'সামনের' : 'পেছনের'} দিক`}><div className="relative aspect-[1.586/1] overflow-hidden bg-gradient-to-br from-sky-50 via-white to-brand-50 p-3"><div className="absolute -right-9 -top-10 h-32 w-32 rounded-full bg-brand-100/70" /><div className="absolute -bottom-12 -left-8 h-28 w-36 -rotate-12 rounded-full bg-sky-100/70" />{isFront ? <div className="relative flex h-full flex-col"><div className="flex items-center justify-between"><div className="flex items-center gap-1.5 text-[10px] font-bold text-brand-800"><ShieldCheck size={13} />পরিচয় যাচাইয়ের উদাহরণ</div><span className="text-[9px] font-semibold text-ink-400">FRONT</span></div><div className="mt-3 flex flex-1 gap-3"><div className="relative flex h-16 w-12 shrink-0 items-end justify-center overflow-hidden rounded-md border border-sky-200 bg-sky-100"><span className="mb-7 h-7 w-7 rounded-full bg-sky-200" /><span className="absolute bottom-0 h-7 w-10 rounded-t-full bg-brand-200" /></div><div className="flex-1 space-y-2 pt-1"><span className="block h-2.5 w-4/5 rounded bg-sky-200" /><span className="block h-2 w-full rounded bg-sky-100" /><span className="block h-2 w-3/4 rounded bg-sky-100" /><span className="block h-2 w-2/3 rounded bg-sky-100" /></div></div><div className="flex items-end justify-between"><span className="h-2 w-3/5 rounded bg-sky-100" /><span className="text-[8px] font-bold tracking-[0.14em] text-brand-500">SAMPLE</span></div></div> : <div className="relative flex h-full flex-col"><div className="flex items-center justify-between"><span className="text-[10px] font-bold text-brand-800">পরিচয়পত্রের তথ্য ও QR অংশ</span><span className="text-[9px] font-semibold text-ink-400">BACK</span></div><div className="mt-3 grid flex-1 grid-cols-[1fr_auto] gap-4"><div className="space-y-2"><span className="block h-2.5 w-full rounded bg-sky-200" /><span className="block h-2 w-11/12 rounded bg-sky-100" /><span className="block h-2 w-4/5 rounded bg-sky-100" /><span className="block h-2 w-3/5 rounded bg-sky-100" /><div className="mt-3 h-5 rounded-sm bg-sky-100" /></div><div className="flex flex-col items-center justify-end gap-2"><div className="grid h-14 w-14 place-items-center rounded-md border border-sky-200 bg-white text-brand-600"><QrCode size={32} /></div><span className="text-[8px] font-bold text-ink-500">QR / BARCODE</span></div></div><div className="flex items-center gap-1 text-[8px] font-semibold text-brand-600"><ScanFace size={11} />QR/barcode অংশ যেন পরিষ্কার থাকে</div></div>}</div></GuideShell>
}

export function NidSelfieGuideCard() {
  return <GuideShell label="NID হাতে সেলফি"><div className="relative aspect-[1.55/1] overflow-hidden bg-gradient-to-br from-brand-50 via-white to-emerald-50 p-4"><div className="absolute -right-5 -top-9 h-28 w-28 rounded-full bg-amber-100/70" /><div className="relative flex h-full items-center justify-center gap-5"><div className="relative flex h-[118px] w-[82px] flex-col items-center overflow-hidden rounded-[18px] border-[5px] border-ink-700 bg-white pt-3 shadow-sm"><span className="h-9 w-9 rounded-full bg-amber-200" /><span className="mt-1 h-12 w-14 rounded-t-[28px] bg-brand-200" /><span className="absolute bottom-1 h-1 w-8 rounded-full bg-ink-200" /></div><div className="relative -ml-9 mt-9 w-[95px] rotate-[-7deg] rounded-lg border-2 border-brand-200 bg-white p-2 shadow-md"><div className="flex items-center gap-1"><span className="h-6 w-5 rounded bg-brand-100" /><span className="h-1.5 flex-1 rounded bg-brand-100" /></div><span className="mt-2 block h-1.5 w-full rounded bg-brand-50" /><span className="mt-1 block h-1.5 w-3/4 rounded bg-brand-50" /><span className="mt-2 block text-[8px] font-extrabold tracking-[0.1em] text-brand-600">ID CARD</span></div></div><div className="absolute bottom-3 left-3 flex items-center gap-1 rounded-full bg-white/90 px-2 py-1 text-[9px] font-bold text-brand-700 shadow-sm"><CheckCircle2 size={11} />মুখ ও কার্ড এক ফ্রেমে</div></div></GuideShell>
}

export function OwnershipProofGuideCard() {
  return <GuideShell label="ডিজিটাল পণ্যের মালিকানার প্রমাণ"><div className="relative aspect-[1.55/1] overflow-hidden bg-gradient-to-br from-brand-50 via-white to-sky-50 p-4"><div className="absolute -bottom-12 -right-8 h-36 w-36 rounded-full bg-brand-100/70" /><div className="relative mx-auto max-w-[255px] rounded-lg border border-outline bg-white p-3 shadow-sm"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-brand-50 text-brand-700"><FileCheck2 size={17} /></span><div><span className="block h-2 w-24 rounded bg-ink-200" /><span className="mt-1 block h-1.5 w-16 rounded bg-brand-100" /></div></div><span className="rounded bg-brand-50 px-1.5 py-1 text-[8px] font-bold text-brand-700">প্রমাণ</span></div><div className="mt-4 space-y-2"><span className="block h-2 w-full rounded bg-ink-100" /><span className="block h-2 w-5/6 rounded bg-ink-100" /><span className="block h-2 w-3/5 rounded bg-ink-100" /></div><div className="mt-4 flex items-center gap-2"><span className="h-7 w-20 rounded bg-brand-100" /><span className="flex h-7 flex-1 items-center justify-center rounded border border-brand-200 text-[8px] font-bold text-brand-700">LICENSE / INVOICE</span></div></div><div className="absolute bottom-3 left-3 flex items-center gap-1 rounded-full bg-white/90 px-2 py-1 text-[9px] font-bold text-brand-700 shadow-sm"><CheckCircle2 size={11} />লেখা ও মালিকানার তথ্য দেখান</div></div></GuideShell>
}
