import { QrCode, ScanFace, ShieldCheck } from 'lucide-react'

export function NidGuideCard({ side }: { side: 'front' | 'back' }) {
  const isFront = side === 'front'
  return <div className="w-full max-w-[340px] overflow-hidden rounded-lg border border-brand-200 bg-white shadow-sm" aria-label={isFront ? 'NID সামনের দিকের নিরাপদ নমুনা' : 'NID পেছনের দিকের নিরাপদ নমুনা'}>
    <div className="flex items-center justify-between border-b border-brand-100 bg-brand-50 px-3 py-1.5"><span className="text-[10px] font-extrabold tracking-[0.12em] text-brand-800">পরিচয়পত্রের {isFront ? 'সামনের' : 'পেছনের'} দিক</span><span className="rounded-full bg-amber-100 px-2 py-0.5 text-[9px] font-bold text-amber-900">নমুনা • আসল NID নয়</span></div>
    <div className="relative aspect-[1.586/1] overflow-hidden bg-gradient-to-br from-sky-50 via-white to-brand-50 p-3"><div className="absolute -right-9 -top-10 h-32 w-32 rounded-full bg-brand-100/70" /><div className="absolute -bottom-12 -left-8 h-28 w-36 -rotate-12 rounded-full bg-sky-100/70" />
      {isFront ? <div className="relative flex h-full flex-col"><div className="flex items-center justify-between"><div className="flex items-center gap-1.5 text-[10px] font-bold text-brand-800"><ShieldCheck size={13} />পরিচয় যাচাইয়ের উদাহরণ</div><span className="text-[9px] font-semibold text-ink-400">FRONT</span></div><div className="mt-3 flex flex-1 gap-3"><div className="flex h-16 w-12 shrink-0 items-end justify-center overflow-hidden rounded-md border border-sky-200 bg-sky-100"><span className="h-9 w-9 rounded-full bg-sky-200" /><span className="absolute mb-0 h-6 w-10 rounded-t-full bg-brand-200" /></div><div className="flex-1 space-y-2 pt-1"><span className="block h-2.5 w-4/5 rounded bg-sky-200" /><span className="block h-2 w-full rounded bg-sky-100" /><span className="block h-2 w-3/4 rounded bg-sky-100" /><span className="block h-2 w-2/3 rounded bg-sky-100" /></div></div><div className="flex items-end justify-between"><span className="h-2 w-3/5 rounded bg-sky-100" /><span className="text-[8px] font-bold tracking-[0.14em] text-brand-500">SAMPLE</span></div></div> : <div className="relative flex h-full flex-col"><div className="flex items-center justify-between"><span className="text-[10px] font-bold text-brand-800">পরিচয়পত্রের তথ্য ও QR অংশ</span><span className="text-[9px] font-semibold text-ink-400">BACK</span></div><div className="mt-3 grid flex-1 grid-cols-[1fr_auto] gap-4"><div className="space-y-2"><span className="block h-2.5 w-full rounded bg-sky-200" /><span className="block h-2 w-11/12 rounded bg-sky-100" /><span className="block h-2 w-4/5 rounded bg-sky-100" /><span className="block h-2 w-3/5 rounded bg-sky-100" /><div className="mt-3 h-5 rounded-sm bg-sky-100" /></div><div className="flex flex-col items-center justify-end gap-2"><div className="grid h-14 w-14 place-items-center rounded-md border border-sky-200 bg-white text-brand-600"><QrCode size={32} /></div><span className="text-[8px] font-bold text-ink-500">QR / BARCODE</span></div></div><div className="flex items-center gap-1 text-[8px] font-semibold text-brand-600"><ScanFace size={11} />QR/barcode অংশ যেন পরিষ্কার থাকে</div></div>}
    </div>
  </div>
}
