-- 071_security_definer_hardening.sql
--
-- The web app uses Firebase UID verification in the Vercel gateway for admin,
-- wallet, order and notification server handlers. SECURITY DEFINER functions
-- that accept explicit IDs must not remain broadly callable by anon/authenticated
-- roles. Public-safe read functions and the browser-facing admin_access RPC are
-- intentionally preserved.

-- 1) Fix every public SECURITY DEFINER function that still has a mutable or
-- unspecified search_path. The identity-argument string is generated by
-- PostgreSQL, so overloaded functions are altered precisely.
do $$
declare
  item record;
begin
  for item in
    select n.nspname as schema_name,
           p.proname as function_name,
           pg_get_function_identity_arguments(p.oid) as identity_args
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.prosecdef = true
      and p.proconfig is null
  loop
    execute format(
      'alter function %I.%I(%s) set search_path = public, pg_temp',
      item.schema_name,
      item.function_name,
      item.identity_args
    );
  end loop;
end;
$$;

-- 2) Admin operations are called through /api/admin-rpc, which verifies the
-- Firebase ID token and passes the verified UID as p_admin_id. Keep only the
-- browser-facing admin_access discovery RPC directly callable.
do $$
declare
  item record;
begin
  for item in
    select n.nspname as schema_name,
           p.proname as function_name,
           pg_get_function_identity_arguments(p.oid) as identity_args
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and left(p.proname, 6) = 'admin_'
      and p.proname <> 'admin_access'
  loop
    execute format(
      'revoke all on function %I.%I(%s) from public, anon, authenticated',
      item.schema_name,
      item.function_name,
      item.identity_args
    );
    execute format(
      'grant execute on function %I.%I(%s) to service_role',
      item.schema_name,
      item.function_name,
      item.identity_args
    );
  end loop;
end;
$$;

-- is_admin is an internal helper. admin_access remains the only direct admin
-- discovery function used by the browser hook.
revoke all on function public.is_admin(text) from public, anon, authenticated;
grant execute on function public.is_admin(text) to service_role;

-- 3) Trigger/webhook/ledger helpers have no legitimate direct browser caller.
-- They are invoked by triggers, SECURITY DEFINER functions, or the verified
-- server gateway. Revoke direct execution while keeping service_role access.
do $$
declare
  item record;
begin
  for item in
    select n.nspname as schema_name,
           p.proname as function_name,
           pg_get_function_identity_arguments(p.oid) as identity_args
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname in (
        'apply_order_wallet_effects',
        'apply_paid_withdrawal',
        'apply_seller_registration_review',
        'apply_wallet_ledger_entry',
        'enqueue_notification_push_webhook',
        'force_new_product_pending',
        'notify_chat_message_event',
        'notify_order_change',
        'notify_product_admin_review',
        'notify_product_question_event',
        'notify_seller_verification_event',
        'notify_user_event',
        'notify_wallet_event',
        'notify_withdrawal_review_event',
        'queue_notification_push_deliveries',
        'refresh_order_dispute_status',
        'refresh_seller_rating',
        'release_pending_coupon_on_cancel',
        'reset_product_approval_on_edit',
        'rls_auto_enable',
        'sync_digital_delivery',
        'sync_wallet_balance'
      )
  loop
    execute format(
      'revoke all on function %I.%I(%s) from public, anon, authenticated',
      item.schema_name,
      item.function_name,
      item.identity_args
    );
    execute format(
      'grant execute on function %I.%I(%s) to service_role',
      item.schema_name,
      item.function_name,
      item.identity_args
    );
  end loop;
end;
$$;

-- Keep the intended browser-safe public functions and admin_access untouched.
-- Tables with RLS enabled and no policy remain service_role/RPC-only by design;
-- no blanket policy is added here because a permissive policy would expose
-- admin, notification, verification or audit data through the browser client.
