-- Broaden the seller catalog with category-neutral digital goods and service types.
-- These categories deliberately avoid third-party brand claims and do not request credentials.
insert into public.categories (id, name, icon_url, sort_order)
values
  ('digital_productivity_tools', 'প্রোডাক্টিভিটি টুল / SaaS', null, 130),
  ('digital_cloud_storage', 'ক্লাউড স্টোরেজ / ব্যাকআপ', null, 140),
  ('digital_security_privacy', 'সিকিউরিটি / প্রাইভেসি টুল', null, 150),
  ('digital_developer_tools', 'ডেভেলপার টুল / API অ্যাসেট', null, 160),
  ('digital_domain_hosting', 'ডোমেইন / হোস্টিং সার্ভিস', null, 170),
  ('digital_collaboration_tools', 'কলাবোরেশন / অফিস টুল', null, 180),
  ('digital_ai_creative_tools', 'AI / ক্রিয়েটিভ টুল', null, 190),
  ('digital_marketing_services', 'ডিজিটাল মার্কেটিং সার্ভিস', null, 200),
  ('digital_business_templates', 'বিজনেস টেমপ্লেট / ডকুমেন্ট', null, 210),
  ('digital_resume_portfolio', 'রেজ্যুমে / পোর্টফোলিও অ্যাসেট', null, 220),
  ('digital_learning_resources', 'লার্নিং রিসোর্স / স্টাডি ম্যাটেরিয়াল', null, 230),
  ('digital_stock_media', 'স্টক মিডিয়া / অডিও / ভিডিও অ্যাসেট', null, 240),
  ('digital_mobile_utilities', 'মোবাইল অ্যাপ / ইউটিলিটি', null, 250),
  ('digital_website_services', 'ওয়েবসাইট / ই-কমার্স সার্ভিস', null, 260)
on conflict (id) do update set name = excluded.name, sort_order = excluded.sort_order;

insert into public.digital_category_templates (category_id, name_en, description_bn, icon_key, fields, sort_order, is_active)
values
  ('digital_productivity_tools', 'Productivity Tool / SaaS', 'বৈধভাবে বিক্রয়যোগ্য productivity tool বা SaaS service-এর plan, মেয়াদ ও region দিন; কোনো account credential দেবেন না।', 'Package', '[{"key":"tool_type","label_bn":"টুলের ধরন","type":"text","required":true},{"key":"plan_name","label_bn":"Plan / package","type":"text","required":true},{"key":"subscription_period","label_bn":"মেয়াদ","type":"text","required":true},{"key":"region_code","label_bn":"Region","type":"text","required":false}]'::jsonb, 130, true),
  ('digital_cloud_storage', 'Cloud Storage / Backup', 'বৈধ cloud storage বা backup offer-এর capacity, মেয়াদ ও region দিন; ব্যক্তিগত account password চাইবেন না।', 'Package', '[{"key":"service_type","label_bn":"সার্ভিসের ধরন","type":"text","required":true},{"key":"storage_capacity","label_bn":"Storage capacity","type":"text","required":true},{"key":"subscription_period","label_bn":"মেয়াদ","type":"text","required":true},{"key":"region_code","label_bn":"Region","type":"text","required":false}]'::jsonb, 140, true),
  ('digital_security_privacy', 'Security / Privacy Tool', 'বৈধ security, privacy বা device-protection product-এর scope ও মেয়াদ দিন।', 'Package', '[{"key":"service_type","label_bn":"সার্ভিসের ধরন","type":"text","required":true},{"key":"coverage_scope","label_bn":"কভারেজ / device scope","type":"text","required":true},{"key":"subscription_period","label_bn":"মেয়াদ","type":"text","required":true},{"key":"region_code","label_bn":"Region","type":"text","required":false}]'::jsonb, 150, true),
  ('digital_developer_tools', 'Developer Tool / API Asset', 'নিজের বা বৈধভাবে পুনর্বিক্রয়যোগ্য developer tool, code asset বা documentation resource-এর তথ্য দিন।', 'Package', '[{"key":"asset_type","label_bn":"টুল / asset-এর ধরন","type":"text","required":true},{"key":"compatibility","label_bn":"Compatibility","type":"text","required":true},{"key":"license_type","label_bn":"Usage license","type":"text","required":true},{"key":"included_items","label_bn":"Included items","type":"textarea","required":false}]'::jsonb, 160, true),
  ('digital_domain_hosting', 'Domain / Hosting Service', 'ডোমেইন, hosting বা website maintenance service-এর মেয়াদ, scope ও transfer policy পরিষ্কারভাবে দিন।', 'Package', '[{"key":"service_type","label_bn":"সার্ভিসের ধরন","type":"text","required":true},{"key":"term","label_bn":"মেয়াদ","type":"text","required":true},{"key":"scope","label_bn":"Scope / limit","type":"text","required":true},{"key":"transfer_policy","label_bn":"Transfer / renewal policy","type":"textarea","required":false}]'::jsonb, 170, true),
  ('digital_collaboration_tools', 'Collaboration / Office Tool', 'বৈধ team collaboration বা office productivity product-এর plan, user limit ও access period দিন।', 'Package', '[{"key":"tool_type","label_bn":"টুলের ধরন","type":"text","required":true},{"key":"plan_name","label_bn":"Plan / package","type":"text","required":true},{"key":"user_limit","label_bn":"User / device limit","type":"text","required":false},{"key":"subscription_period","label_bn":"মেয়াদ","type":"text","required":true}]'::jsonb, 180, true),
  ('digital_ai_creative_tools', 'AI / Creative Tool', 'নিজের বা বৈধভাবে সরবরাহযোগ্য AI, creative tool বা credit package-এর scope ও usage right দিন।', 'Package', '[{"key":"tool_type","label_bn":"টুলের ধরন","type":"text","required":true},{"key":"usage_scope","label_bn":"Usage scope","type":"text","required":true},{"key":"subscription_period","label_bn":"মেয়াদ","type":"text","required":false},{"key":"usage_rights","label_bn":"Usage rights","type":"text","required":true}]'::jsonb, 190, true),
  ('digital_marketing_services', 'Digital Marketing Service', 'বাস্তবসম্মত marketing service-এর platform, কাজের পরিধি ও delivery window দিন; ফলাফল নিয়ে বিভ্রান্তিকর প্রতিশ্রুতি দেবেন না।', 'Package', '[{"key":"service_type","label_bn":"সার্ভিসের ধরন","type":"text","required":true},{"key":"platform","label_bn":"Platform","type":"text","required":true},{"key":"service_scope","label_bn":"কাজের পরিধি","type":"textarea","required":true},{"key":"delivery_window","label_bn":"Delivery window","type":"text","required":true}]'::jsonb, 200, true),
  ('digital_business_templates', 'Business Template / Document', 'নিজের তৈরি বা বৈধ licence-সহ business template, document বা spreadsheet-এর format ও usage license দিন।', 'Package', '[{"key":"template_type","label_bn":"Template-এর ধরন","type":"text","required":true},{"key":"file_format","label_bn":"File format","type":"text","required":true},{"key":"language","label_bn":"ভাষা","type":"text","required":true},{"key":"usage_license","label_bn":"Usage license","type":"text","required":true}]'::jsonb, 210, true),
  ('digital_resume_portfolio', 'Resume / Portfolio Asset', 'নিজের তৈরি resume, portfolio, CV বা career asset-এর format ও editable file information দিন।', 'Package', '[{"key":"asset_type","label_bn":"Asset-এর ধরন","type":"text","required":true},{"key":"file_format","label_bn":"File format","type":"text","required":true},{"key":"language","label_bn":"ভাষা","type":"text","required":true},{"key":"editable","label_bn":"Editable file আছে?","type":"boolean","required":false}]'::jsonb, 220, true),
  ('digital_learning_resources', 'Learning Resource / Study Material', 'নিজের তৈরি বা বৈধভাবে বিক্রয়যোগ্য study material-এর subject, level, language ও included file দিন।', 'Package', '[{"key":"resource_type","label_bn":"রিসোর্সের ধরন","type":"text","required":true},{"key":"subject","label_bn":"বিষয়","type":"text","required":true},{"key":"level","label_bn":"লেভেল","type":"text","required":true},{"key":"language","label_bn":"ভাষা","type":"text","required":true}]'::jsonb, 230, true),
  ('digital_stock_media', 'Stock Media / Audio / Video Asset', 'নিজের বা বৈধ licence-সহ stock media, sound, video বা creative asset-এর format ও usage rights দিন।', 'Package', '[{"key":"asset_type","label_bn":"Asset-এর ধরন","type":"text","required":true},{"key":"file_format","label_bn":"File format","type":"text","required":true},{"key":"usage_license","label_bn":"Usage license","type":"text","required":true},{"key":"included_files","label_bn":"Included files","type":"textarea","required":false}]'::jsonb, 240, true),
  ('digital_mobile_utilities', 'Mobile App / Utility', 'নিজের বা বৈধভাবে সরবরাহযোগ্য mobile utility, premium feature বা app-related service-এর platform ও scope দিন।', 'Package', '[{"key":"utility_type","label_bn":"Utility-এর ধরন","type":"text","required":true},{"key":"platform","label_bn":"Platform","type":"select","required":true,"options":["Android","iOS","Both"]},{"key":"service_scope","label_bn":"Service scope","type":"textarea","required":true},{"key":"subscription_period","label_bn":"মেয়াদ","type":"text","required":false}]'::jsonb, 250, true),
  ('digital_website_services', 'Website / E-commerce Service', 'ওয়েবসাইট, store setup, maintenance বা design service-এর scope, handover ও delivery window দিন।', 'Package', '[{"key":"service_type","label_bn":"সার্ভিসের ধরন","type":"text","required":true},{"key":"service_scope","label_bn":"কাজের পরিধি","type":"textarea","required":true},{"key":"handover_items","label_bn":"Handover items","type":"textarea","required":false},{"key":"delivery_window","label_bn":"Delivery window","type":"text","required":true}]'::jsonb, 260, true)
on conflict (category_id) do update set
  name_en = excluded.name_en,
  description_bn = excluded.description_bn,
  icon_key = excluded.icon_key,
  fields = excluded.fields,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();
