begin;

create table if not exists public.support_chats (
  id uuid primary key default gen_random_uuid(),
  customer_id text not null unique references public.profiles(id),
  last_message text not null default '',
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.support_cases (
  id uuid primary key default gen_random_uuid(),
  support_chat_id uuid not null references public.support_chats(id) on delete cascade,
  case_number bigint generated by default as identity unique,
  category text not null check (category in ('ORDER_PRODUCT', 'PAYMENT', 'ACCOUNT_SECURITY', 'REPORT_COMPLAINT', 'OTHER')),
  status text not null default 'OPEN' check (status in ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
  order_id uuid references public.orders(id) on delete set null,
  subject text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.support_case_messages (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.support_cases(id) on delete cascade,
  sender_id text not null references public.profiles(id),
  sender_role text not null default 'CUSTOMER' check (sender_role in ('CUSTOMER', 'SUPPORT')),
  text text not null check (length(trim(text)) between 1 and 5000),
  created_at timestamptz not null default now()
);

create index if not exists idx_support_cases_chat_updated on public.support_cases(support_chat_id, updated_at desc);
create index if not exists idx_support_case_messages_case_created on public.support_case_messages(case_id, created_at);

alter table public.support_chats enable row level security;
alter table public.support_cases enable row level security;
alter table public.support_case_messages enable row level security;

drop policy if exists "Support chats are gateway protected" on public.support_chats;
drop policy if exists "Support cases are gateway protected" on public.support_cases;
drop policy if exists "Support case messages are gateway protected" on public.support_case_messages;
create policy "Support chats are gateway protected" on public.support_chats for all using (false) with check (false);
create policy "Support cases are gateway protected" on public.support_cases for all using (false) with check (false);
create policy "Support case messages are gateway protected" on public.support_case_messages for all using (false) with check (false);

create or replace function public.get_or_create_support_chat(p_customer_id text)
returns public.support_chats as $$
declare v_chat public.support_chats;
begin
  insert into public.support_chats(customer_id) values (p_customer_id)
  on conflict (customer_id) do update set customer_id = excluded.customer_id
  returning * into v_chat;
  return v_chat;
end;
$$ language plpgsql security definer set search_path = public, pg_temp;

create or replace function public.list_my_support_cases(p_customer_id text)
returns table(id uuid, support_chat_id uuid, case_number bigint, category text, status text, order_id uuid, subject text, created_at timestamptz, updated_at timestamptz, resolved_at timestamptz, last_message text, message_count bigint) as $$
begin
  return query
  select c.id, c.support_chat_id, c.case_number, c.category, c.status, c.order_id, c.subject, c.created_at, c.updated_at, c.resolved_at,
    coalesce((select m.text from public.support_case_messages m where m.case_id = c.id order by m.created_at desc limit 1), ''),
    (select count(*) from public.support_case_messages m where m.case_id = c.id)
  from public.support_cases c join public.support_chats s on s.id = c.support_chat_id
  where s.customer_id = p_customer_id order by c.updated_at desc;
end;
$$ language plpgsql security definer stable set search_path = public, pg_temp;

create or replace function public.create_my_support_case(p_customer_id text, p_category text, p_subject text, p_order_id uuid default null, p_initial_message text default null)
returns public.support_cases as $$
declare v_chat public.support_chats; v_case public.support_cases; v_text text;
begin
  if p_category not in ('ORDER_PRODUCT', 'PAYMENT', 'ACCOUNT_SECURITY', 'REPORT_COMPLAINT', 'OTHER') then raise exception 'Invalid support category'; end if;
  if length(trim(coalesce(p_subject, ''))) < 1 then raise exception 'Support subject is required'; end if;
  if p_order_id is not null and not exists (select 1 from public.orders o where o.id = p_order_id and o.buyer_id = p_customer_id) then raise exception 'Order is not yours'; end if;
  v_chat := public.get_or_create_support_chat(p_customer_id);
  insert into public.support_cases(support_chat_id, category, subject, order_id) values (v_chat.id, p_category, trim(p_subject), p_order_id) returning * into v_case;
  v_text := nullif(trim(coalesce(p_initial_message, '')), '');
  if v_text is not null then insert into public.support_case_messages(case_id, sender_id, sender_role, text) values (v_case.id, p_customer_id, 'CUSTOMER', v_text); end if;
  update public.support_chats set last_message = coalesce(v_text, 'নতুন সাপোর্ট কেস খোলা হয়েছে'), last_message_at = now() where id = v_chat.id;
  return v_case;
end;
$$ language plpgsql security definer set search_path = public, pg_temp;

create or replace function public.list_my_support_case_messages(p_customer_id text, p_case_id uuid)
returns setof public.support_case_messages as $$
begin
  if not exists (select 1 from public.support_cases c join public.support_chats s on s.id = c.support_chat_id where c.id = p_case_id and s.customer_id = p_customer_id) then raise exception 'Support case not found or not yours'; end if;
  return query select m.* from public.support_case_messages m where m.case_id = p_case_id order by m.created_at asc;
end;
$$ language plpgsql security definer stable set search_path = public, pg_temp;

create or replace function public.send_my_support_case_message(p_customer_id text, p_case_id uuid, p_text text)
returns uuid as $$
declare v_message_id uuid; v_chat_id uuid;
begin
  if length(trim(coalesce(p_text, ''))) not between 1 and 5000 then raise exception 'Message must be between 1 and 5000 characters'; end if;
  select c.support_chat_id into v_chat_id from public.support_cases c join public.support_chats s on s.id = c.support_chat_id where c.id = p_case_id and s.customer_id = p_customer_id and c.status in ('OPEN', 'IN_PROGRESS');
  if v_chat_id is null then raise exception 'Support case is not open'; end if;
  insert into public.support_case_messages(case_id, sender_id, sender_role, text) values (p_case_id, p_customer_id, 'CUSTOMER', trim(p_text)) returning id into v_message_id;
  update public.support_cases set updated_at = now() where id = p_case_id;
  update public.support_chats set last_message = trim(p_text), last_message_at = now() where id = v_chat_id;
  return v_message_id;
end;
$$ language plpgsql security definer set search_path = public, pg_temp;

revoke all on function public.get_or_create_support_chat(text) from public, anon, authenticated;
revoke all on function public.list_my_support_cases(text) from public, anon, authenticated;
revoke all on function public.create_my_support_case(text, text, text, uuid, text) from public, anon, authenticated;
revoke all on function public.list_my_support_case_messages(text, uuid) from public, anon, authenticated;
revoke all on function public.send_my_support_case_message(text, uuid, text) from public, anon, authenticated;
grant execute on function public.get_or_create_support_chat(text) to service_role;
grant execute on function public.list_my_support_cases(text) to service_role;
grant execute on function public.create_my_support_case(text, text, text, uuid, text) to service_role;
grant execute on function public.list_my_support_case_messages(text, uuid) to service_role;
grant execute on function public.send_my_support_case_message(text, uuid, text) to service_role;

commit;

-- Customer-scoped Support Center: one support chat per customer, many isolated cases.
