-- Bikrify brand story content
-- Keeps public pages, privacy language and the blog aligned around Bikrify as
-- BikriKoro's authentication brand.

do $$
declare
  v_id uuid;
begin
  -- About page
  select id into v_id from public.admin_content where content_type = 'ABOUT' order by updated_at desc limit 1;
  if v_id is null then
    insert into public.admin_content(content_type, title, slug, excerpt, body, status, seo_title, seo_description, published_at)
    values ('ABOUT', 'Bikrify — BikriKoro-এর authentication brand', 'about', 'Bikrify হলো BikriKoro-এর পরিচয় ও authentication brand—যা approved NID, business বা company verification-এর পর seller profile-এ দেখা যায়।', E'Bikrify কী?\n\nBikrify হলো BikriKoro-এর authentication brand—একটি দৃশ্যমান trust signal, যা buyer-কে বুঝতে সাহায্য করে যে একজন seller BikriKoro-এর নির্দিষ্ট verification process সম্পন্ন করেছেন। এটি শুধু একটি icon নয়; এটি পরিচয়, তথ্যের সামঞ্জস্য এবং দায়িত্বশীল marketplace আচরণের প্রতি আমাদের অঙ্গীকার।\n\nকীভাবে Bikrify পাওয়া যায়?\n\nযে seller NID দিয়ে identity verification pass করেন, অথবা business/company হিসেবে প্রয়োজনীয় তথ্য ও documents জমা দিয়ে approval পান, তাদের profile-এ Bikrify badge দেখা যায়। সাধারণ user product listing করতে পারবেন, কিন্তু verification approval ছাড়া Bikrify badge পাবেন না।\n\nBuyer-এর জন্য এর অর্থ কী?\n\nBikrify buyer-কে একটি starting point দেয়—কাকে নিয়ে আরও তথ্য দেখা উচিত তা বুঝতে সাহায্য করে। তবে badge কোনো transaction-এর গ্যারান্টি নয়। কেনার আগে product description, price, delivery method, review, chat এবং order flow নিজে যাচাই করুন।\n\nBikrify আমাদের প্রতিশ্রুতি\n\nআমরা trust-কে একবারের label হিসেবে নয়, বরং চলমান দায়িত্ব হিসেবে দেখি। তাই seller-এর profile তথ্য, marketplace rules, order history এবং support process—সবকিছুর সাথে Bikrify-কে দায়িত্বশীলভাবে ব্যবহার করি।', 'PUBLISHED', 'Bikrify কী? | BikriKoro authentication brand', 'Bikrify হলো BikriKoro-এর authentication brand—approved seller verification-এর দৃশ্যমান trust signal।', now());
  else
    update public.admin_content set title='Bikrify — BikriKoro-এর authentication brand', slug='about', excerpt='Bikrify হলো BikriKoro-এর পরিচয় ও authentication brand—যা approved NID, business বা company verification-এর পর seller profile-এ দেখা যায়।', body=E'Bikrify কী?\n\nBikrify হলো BikriKoro-এর authentication brand—একটি দৃশ্যমান trust signal, যা buyer-কে বুঝতে সাহায্য করে যে একজন seller BikriKoro-এর নির্দিষ্ট verification process সম্পন্ন করেছেন। এটি শুধু একটি icon নয়; এটি পরিচয়, তথ্যের সামঞ্জস্য এবং দায়িত্বশীল marketplace আচরণের প্রতি আমাদের অঙ্গীকার।\n\nকীভাবে Bikrify পাওয়া যায়?\n\nযে seller NID দিয়ে identity verification pass করেন, অথবা business/company হিসেবে প্রয়োজনীয় তথ্য ও documents জমা দিয়ে approval পান, তাদের profile-এ Bikrify badge দেখা যায়। সাধারণ user product listing করতে পারবেন, কিন্তু verification approval ছাড়া Bikrify badge পাবেন না।\n\nBuyer-এর জন্য এর অর্থ কী?\n\nBikrify buyer-কে একটি starting point দেয়—কাকে নিয়ে আরও তথ্য দেখা উচিত তা বুঝতে সাহায্য করে। তবে badge কোনো transaction-এর গ্যারান্টি নয়। কেনার আগে product description, price, delivery method, review, chat এবং order flow নিজে যাচাই করুন।\n\nBikrify আমাদের প্রতিশ্রুতি\n\nআমরা trust-কে একবারের label হিসেবে নয়, বরং চলমান দায়িত্ব হিসেবে দেখি। তাই seller-এর profile তথ্য, marketplace rules, order history এবং support process—সবকিছুর সাথে Bikrify-কে দায়িত্বশীলভাবে ব্যবহার করি।', status='PUBLISHED', seo_title='Bikrify কী? | BikriKoro authentication brand', seo_description='Bikrify হলো BikriKoro-এর authentication brand—approved seller verification-এর দৃশ্যমান trust signal।', published_at=coalesce(published_at, now()), updated_at=now() where id=v_id;
  end if;

  -- Main privacy policy
  select id into v_id from public.admin_content where content_type = 'PRIVACY' order by updated_at desc limit 1;
  if v_id is null then
    insert into public.admin_content(content_type, title, slug, excerpt, body, status, seo_title, seo_description, published_at)
    values ('PRIVACY', 'প্রাইভেসি পলিসি', 'privacy', 'BikriKoro ও Bikrify verification process-এ আপনার তথ্য কীভাবে সংগ্রহ, ব্যবহার ও সুরক্ষিত করা হয়।', E'Bikrify verification ও আপনার privacy\n\nBikrify badge দেখানোর জন্য আমরা কেবল verification-এর ফলাফল—যেমন approval status—public seller profile-এ ব্যবহার করি। NID, selfie, trade license, company document বা verification-এর sensitive ছবি কখনো public profile, product listing বা blog-এ প্রকাশ করা হয় না।\n\nআমরা যে verification তথ্য ব্যবহার করি\n\nNID বা business/company registration-এর প্রয়োজনীয় তথ্য ও documents verification review-এর জন্য সংগ্রহ করা হতে পারে। এই তথ্য identity ও business claim যাচাই, fraud prevention এবং marketplace safety-এর কাজে ব্যবহৃত হয়।\n\nPublicly কী দেখা যায়\n\nApproval সম্পন্ন হলে seller profile-এ শুধু Bikrify badge এবং প্রাসঙ্গিক public profile information দেখা যেতে পারে। Badge-এর মাধ্যমে কোনো NID number, document image, address বা private contact information প্রকাশ করা হয় না।\n\nতথ্য সংরক্ষণ ও access\n\nVerification documents private storage ও restricted administrative access-এর মধ্যে রাখা হয়। প্রয়োজনীয় সময়ের বেশি sensitive data রাখা না এবং অপ্রয়োজনীয়ভাবে third party-এর সাথে শেয়ার না করার নীতি অনুসরণ করা হয়। আপনার তথ্য সম্পর্কে প্রশ্ন বা deletion request থাকলে Contact page ব্যবহার করুন।', 'PUBLISHED', 'Bikrify verification ও privacy policy | BikriKoro', 'Bikrify verification-এ NID ও business/company documents কীভাবে সুরক্ষিত থাকে এবং public profile-এ কী দেখা যায়।', now());
  else
    update public.admin_content set title='প্রাইভেসি পলিসি', slug='privacy', excerpt='BikriKoro ও Bikrify verification process-এ আপনার তথ্য কীভাবে সংগ্রহ, ব্যবহার ও সুরক্ষিত করা হয়।', body=E'Bikrify verification ও আপনার privacy\n\nBikrify badge দেখানোর জন্য আমরা কেবল verification-এর ফলাফল—যেমন approval status—public seller profile-এ ব্যবহার করি। NID, selfie, trade license, company document বা verification-এর sensitive ছবি কখনো public profile, product listing বা blog-এ প্রকাশ করা হয় না।\n\nআমরা যে verification তথ্য ব্যবহার করি\n\nNID বা business/company registration-এর প্রয়োজনীয় তথ্য ও documents verification review-এর জন্য সংগ্রহ করা হতে পারে। এই তথ্য identity ও business claim যাচাই, fraud prevention এবং marketplace safety-এর কাজে ব্যবহৃত হয়।\n\nPublicly কী দেখা যায়\n\nApproval সম্পন্ন হলে seller profile-এ শুধু Bikrify badge এবং প্রাসঙ্গিক public profile information দেখা যেতে পারে। Badge-এর মাধ্যমে কোনো NID number, document image, address বা private contact information প্রকাশ করা হয় না।\n\nতথ্য সংরক্ষণ ও access\n\nVerification documents private storage ও restricted administrative access-এর মধ্যে রাখা হয়। প্রয়োজনীয় সময়ের বেশি sensitive data রাখা না এবং অপ্রয়োজনীয়ভাবে third party-এর সাথে শেয়ার না করার নীতি অনুসরণ করা হয়। আপনার তথ্য সম্পর্কে প্রশ্ন বা deletion request থাকলে Contact page ব্যবহার করুন।', status='PUBLISHED', seo_title='Bikrify verification ও privacy policy | BikriKoro', seo_description='Bikrify verification-এ NID ও business/company documents কীভাবে সুরক্ষিত থাকে এবং public profile-এ কী দেখা যায়।', published_at=coalesce(published_at, now()), updated_at=now() where id=v_id;
  end if;

  -- Seller privacy page
  select id into v_id from public.admin_content where content_type = 'SELLER_PRIVACY' order by updated_at desc limit 1;
  if v_id is null then
    insert into public.admin_content(content_type, title, slug, excerpt, body, status, seo_title, seo_description, published_at)
    values ('SELLER_PRIVACY', 'Seller Privacy ও Bikrify verification', 'seller-privacy-policy', 'Seller verification, Bikrify approval এবং shop application-এর sensitive তথ্যের ব্যবহার।', E'Bikrify-এর জন্য seller-এর NID বা business/company documents review করা হতে পারে। এই documents-এর উদ্দেশ্য হলো seller identity বা business claim যাচাই করা—marketing material বা public profile-এ documents প্রকাশ করা নয়।\n\nApproval-এর পর public profile-এ Bikrify badge দেখা যেতে পারে, কিন্তু verification document, NID number, selfie বা private review note দেখা যায় না। Seller চাইলে verification-related তথ্য ও access সম্পর্কে Contact page থেকে জানতে পারেন।', 'PUBLISHED', 'Seller Privacy ও Bikrify verification | BikriKoro', 'Seller verification ও Bikrify approval-এর সময় আপনার documents কীভাবে সুরক্ষিত রাখা হয়।', now());
  else
    update public.admin_content set title='Seller Privacy ও Bikrify verification', slug='seller-privacy-policy', excerpt='Seller verification, Bikrify approval এবং shop application-এর sensitive তথ্যের ব্যবহার।', body=E'Bikrify-এর জন্য seller-এর NID বা business/company documents review করা হতে পারে। এই documents-এর উদ্দেশ্য হলো seller identity বা business claim যাচাই করা—marketing material বা public profile-এ documents প্রকাশ করা নয়।\n\nApproval-এর পর public profile-এ Bikrify badge দেখা যেতে পারে, কিন্তু verification document, NID number, selfie বা private review note দেখা যায় না। Seller চাইলে verification-related তথ্য ও access সম্পর্কে Contact page থেকে জানতে পারেন।', status='PUBLISHED', seo_title='Seller Privacy ও Bikrify verification | BikriKoro', seo_description='Seller verification ও Bikrify approval-এর সময় আপনার documents কীভাবে সুরক্ষিত রাখা হয়।', published_at=coalesce(published_at, now()), updated_at=now() where id=v_id;
  end if;

  -- Canonical Bikrify blog article
  select id into v_id from public.admin_content where content_type = 'BLOG' and slug = 'bikrify-authentication-brand' limit 1;
  if v_id is null then
    insert into public.admin_content(content_type, title, slug, excerpt, body, status, seo_title, seo_description, published_at)
    values ('BLOG', 'Bikrify কী? BikriKoro-এর authentication brand বুঝে নিন', 'bikrify-authentication-brand', 'Bikrify শুধু একটি badge নয়—এটি approved seller verification, buyer awareness এবং দায়িত্বশীল digital commerce-এর একটি trust signal।', E'অনলাইনে কেনাকাটার সময় buyer-এর সবচেয়ে গুরুত্বপূর্ণ প্রশ্নগুলোর একটি হলো: এই seller সম্পর্কে আমি কতটা নিশ্চিত হতে পারি? BikriKoro এই প্রশ্নের উত্তরকে আরও সহজ ও দৃশ্যমান করতে তৈরি করেছে Bikrify।\n\nBikrify আসলে কী?\n\nBikrify হলো BikriKoro-এর authentication brand। কোনো seller NID verification pass করলে, অথবা business/company registration ও প্রয়োজনীয় documents review-এর পর approve হলে তার public seller profile-এ Bikrify badge দেখা যায়। সাধারণ user listing করতে পারেন, কিন্তু approval ছাড়া Bikrify identity claim ব্যবহার করতে পারেন না।\n\nBikrify কেন গুরুত্বপূর্ণ?\n\nএকটি marketplace-এ trust তৈরি হয় পরিচয়, পরিষ্কার তথ্য, ভালো আচরণ এবং platform-এর নিয়ম মানার মাধ্যমে। Bikrify buyer-কে দ্রুত একটি starting signal দেয়—এই seller BikriKoro-এর verification process-এর মধ্যে দিয়ে গেছেন। এতে buyer seller profile, product details, reviews ও delivery information আরও মনোযোগ দিয়ে দেখার একটি ভালো কারণ পান।\n\nBadge কি গ্যারান্টি?\n\nনা। Bikrify কোনো product, price বা transaction-এর গ্যারান্টি নয়। এটি verification-এর একটি trust signal। কেনার আগে product description পড়ুন, seller-এর review দেখুন, platform-এর chat ও order flow ব্যবহার করুন এবং অস্বাভাবিক payment request এড়িয়ে চলুন।\n\nSeller কীভাবে Bikrify-এর জন্য প্রস্তুত হবেন?\n\nসঠিক নাম ও profile information দিন, shop details পরিষ্কার রাখুন, NID বা business/company documents যথাযথভাবে জমা দিন এবং buyer-এর প্রশ্নের উত্তর স্বচ্ছভাবে দিন। Approval-এর পরে badge পাওয়া গেলেও trust বজায় রাখতে প্রতিটি listing-এ accurate information ও নিরাপদ delivery অনুসরণ করা জরুরি।\n\nBikrify-এর ভবিষ্যৎ\n\nBikrify-কে আমরা শুধু একটি সবুজ icon হিসেবে দেখি না। এটি BikriKoro-এর authentication language—যার মাধ্যমে identity, responsibility এবং better digital commerce একসাথে প্রকাশ পায়। সময়ের সাথে আমরা verification experience, seller education এবং buyer safety আরও উন্নত করব।\n\nBikrify দেখলে কী করবেন?\n\nBadge-কে একটি helpful signal হিসেবে নিন, তারপর profile, product, price, delivery ও order information যাচাই করে সিদ্ধান্ত নিন। নিরাপদ digital commerce গড়ে ওঠে platform-এর tools এবং buyer-seller—দুই পক্ষের সচেতন ব্যবহারে।', 'PUBLISHED', 'Bikrify কী? BikriKoro-এর authentication brand', 'Bikrify হলো BikriKoro-এর authentication brand—approved seller verification ও নিরাপদ digital commerce-এর trust signal।', now());
  else
    update public.admin_content set title='Bikrify কী? BikriKoro-এর authentication brand বুঝে নিন', excerpt='Bikrify শুধু একটি badge নয়—এটি approved seller verification, buyer awareness এবং দায়িত্বশীল digital commerce-এর একটি trust signal।', body=E'অনলাইনে কেনাকাটার সময় buyer-এর সবচেয়ে গুরুত্বপূর্ণ প্রশ্নগুলোর একটি হলো: এই seller সম্পর্কে আমি কতটা নিশ্চিত হতে পারি? BikriKoro এই প্রশ্নের উত্তরকে আরও সহজ ও দৃশ্যমান করতে তৈরি করেছে Bikrify।\n\nBikrify আসলে কী?\n\nBikrify হলো BikriKoro-এর authentication brand। কোনো seller NID verification pass করলে, অথবা business/company registration ও প্রয়োজনীয় documents review-এর পর approve হলে তার public seller profile-এ Bikrify badge দেখা যায়। সাধারণ user listing করতে পারেন, কিন্তু approval ছাড়া Bikrify identity claim ব্যবহার করতে পারেন না।\n\nBikrify কেন গুরুত্বপূর্ণ?\n\nএকটি marketplace-এ trust তৈরি হয় পরিচয়, পরিষ্কার তথ্য, ভালো আচরণ এবং platform-এর নিয়ম মানার মাধ্যমে। Bikrify buyer-কে দ্রুত একটি starting signal দেয়—এই seller BikriKoro-এর verification process-এর মধ্যে দিয়ে গেছেন। এতে buyer seller profile, product details, reviews ও delivery information আরও মনোযোগ দিয়ে দেখার একটি ভালো কারণ পান।\n\nBadge কি গ্যারান্টি?\n\nনা। Bikrify কোনো product, price বা transaction-এর গ্যারান্টি নয়। এটি verification-এর একটি trust signal। কেনার আগে product description পড়ুন, seller-এর review দেখুন, platform-এর chat ও order flow ব্যবহার করুন এবং অস্বাভাবিক payment request এড়িয়ে চলুন।\n\nSeller কীভাবে Bikrify-এর জন্য প্রস্তুত হবেন?\n\nসঠিক নাম ও profile information দিন, shop details পরিষ্কার রাখুন, NID বা business/company documents যথাযথভাবে জমা দিন এবং buyer-এর প্রশ্নের উত্তর স্বচ্ছভাবে দিন। Approval-এর পরে badge পাওয়া গেলেও trust বজায় রাখতে প্রতিটি listing-এ accurate information ও নিরাপদ delivery অনুসরণ করা জরুরি।\n\nBikrify-এর ভবিষ্যৎ\n\nBikrify-কে আমরা শুধু একটি সবুজ icon হিসেবে দেখি না। এটি BikriKoro-এর authentication language—যার মাধ্যমে identity, responsibility এবং better digital commerce একসাথে প্রকাশ পায়। সময়ের সাথে আমরা verification experience, seller education এবং buyer safety আরও উন্নত করব।\n\nBikrify দেখলে কী করবেন?\n\nBadge-কে একটি helpful signal হিসেবে নিন, তারপর profile, product, price, delivery ও order information যাচাই করে সিদ্ধান্ত নিন। নিরাপদ digital commerce গড়ে ওঠে platform-এর tools এবং buyer-seller—দুই পক্ষের সচেতন ব্যবহারে।', status='PUBLISHED', seo_title='Bikrify কী? BikriKoro-এর authentication brand', seo_description='Bikrify হলো BikriKoro-এর authentication brand—approved seller verification ও নিরাপদ digital commerce-এর trust signal।', published_at=coalesce(published_at, now()), updated_at=now() where id=v_id;
  end if;
end $$;
