-- Bikrify verification FAQ
-- Explains the approved NID and business/company verification paths.
insert into public.admin_content(
  content_type, title, slug, excerpt, body, status, sort_order,
  seo_title, seo_description, published_at
) values
('FAQ', 'Bikrify কী এবং কারা এই badge পাবেন?', 'faq-bikrify-ki-ebong-kara-paben', 'Bikrify হলো BikriKoro-এর approved seller authentication brand।', E'Bikrify হলো BikriKoro-এর একটি দৃশ্যমান authentication brand এবং trust signal। কোনো user product listing করতে পারলেও Bikrify badge শুধুমাত্র সেই seller-এর profile-এ দেখা যায়, যিনি BikriKoro-এর নির্ধারিত verification process সম্পন্ন করে approval পেয়েছেন। NID verification pass করা individual seller অথবা approved business/company seller এই eligibility পেতে পারেন।', 'PUBLISHED', 300, 'Bikrify কী এবং কারা পাবেন | BikriKoro FAQ', 'Bikrify approved seller badge, NID verification এবং business/company approval সম্পর্কে সাধারণ প্রশ্নের উত্তর।', now()),
('FAQ', 'NID দিয়ে Bikrify verification কীভাবে করব?', 'faq-bikrify-nid-verification-process', 'Individual seller-এর NID verification-এর ধাপগুলো।', E'Become Seller বা verification section থেকে individual/NID verification option বেছে নিন। নিজের সঠিক নাম, NID-এর তথ্য এবং প্রয়োজনীয় supporting information দিন। নির্দেশনা অনুযায়ী document বা selfie জমা দিলে admin review team তথ্য যাচাই করবে। তথ্য সঠিক এবং policy অনুযায়ী হলে approval দেওয়া হবে; approval-এর পর আপনার public seller profile-এ Bikrify badge দেখা যাবে। ভুল, অস্পষ্ট বা অন্যের document ব্যবহার করলে verification reject হতে পারে।', 'PUBLISHED', 310, 'NID দিয়ে Bikrify verification করার নিয়ম | BikriKoro FAQ', 'BikriKoro-তে NID verification submit, review এবং Bikrify approval-এর ধাপ।', now()),
('FAQ', 'Business বা company হিসেবে Bikrify approval কীভাবে পাওয়া যায়?', 'faq-bikrify-business-company-verification', 'Business ও company seller-এর verification path।', E'Business বা company registration type বেছে নিয়ে প্রতিষ্ঠানের সঠিক নাম, authorized person-এর তথ্য এবং platform যে business documents চায় সেগুলো জমা দিন। Document-এ থাকা নাম, registration information এবং account profile-এর তথ্যের মধ্যে সামঞ্জস্য থাকতে হবে। Admin review সম্পন্ন হওয়ার পরে approval বা প্রয়োজনীয় correction note দেওয়া হবে। Approval না হওয়া পর্যন্ত profile-এ Bikrify badge দেখাবে না।', 'PUBLISHED', 320, 'Business বা company Bikrify approval | BikriKoro FAQ', 'Business/company seller-এর Bikrify verification documents, review এবং approval process।', now()),
('FAQ', 'Bikrify verification-এর জন্য কোন তথ্য বা document লাগতে পারে?', 'faq-bikrify-verification-documents', 'Verification type অনুযায়ী প্রয়োজনীয় তথ্য আলাদা হতে পারে।', E'Individual verification-এর জন্য NID, নিজের পরিচয়-সংক্রান্ত তথ্য এবং platform-এর নির্দেশনা অনুযায়ী selfie বা supporting information লাগতে পারে। Business/company verification-এর জন্য প্রতিষ্ঠানের registration, authorized person, address বা business document চাওয়া হতে পারে। কোন document লাগবে তা seller type ও review requirement-এর উপর নির্ভর করে; শুধু platform-এর official verification flow-তেই document জমা দিন। Password, OTP বা payment PIN কখনো verification document হিসেবে পাঠাবেন না।', 'PUBLISHED', 330, 'Bikrify verification documents | BikriKoro FAQ', 'NID, business এবং company verification-এর সম্ভাব্য document ও নিরাপত্তা নির্দেশনা।', now()),
('FAQ', 'Bikrify approval হতে কত সময় লাগে এবং status কোথায় দেখব?', 'faq-bikrify-approval-time-status', 'Review queue ও verification status সম্পর্কে জানুন।', E'Approval time document-এর completeness, review queue এবং অতিরিক্ত clarification-এর প্রয়োজনের উপর নির্ভর করে। Verification submit করার পরে seller dashboard বা verification page-এ pending, approved বা rejected status দেখা যেতে পারে। Review চলাকালীন একই document বারবার submit না করে admin-এর note বা correction instruction অনুসরণ করুন। অস্বাভাবিক দেরি হলে আপনার application reference বা account context-সহ Support-এ যোগাযোগ করুন।', 'PUBLISHED', 340, 'Bikrify approval time ও status | BikriKoro FAQ', 'BikriKoro Bikrify verification review status, approval time এবং support নির্দেশনা।', now()),
('FAQ', 'Bikrify badge কি product বা transaction-এর গ্যারান্টি?', 'faq-bikrify-badge-guarantee', 'Badge একটি identity trust signal, সম্পূর্ণ transaction guarantee নয়।', E'না। Bikrify badge দেখায় যে seller BikriKoro-এর নির্দিষ্ট identity বা business/company verification process সম্পন্ন করেছেন। এটি product quality, availability, delivery outcome বা প্রতিটি transaction-এর গ্যারান্টি নয়। কেনার আগে product description, price, seller profile, review, delivery method এবং order flow যাচাই করুন। সমস্যা হলে platform-এর Order Detail, Report বা Dispute path ব্যবহার করুন এবং order-এর বাইরে payment করবেন না।', 'PUBLISHED', 350, 'Bikrify badge কি transaction guarantee | BikriKoro FAQ', 'Bikrify verified seller badge-এর অর্থ, সীমাবদ্ধতা এবং buyer safety নির্দেশনা।', now())
on conflict (slug) do nothing;
