import { useEffect, useMemo, useState } from 'react'
import { Check, CircleHelp, Save } from 'lucide-react'
import { AdminPageHeader, AdminShell, AdminTableCard } from '@/components/admin/AdminShell'
import { useAuth } from '@/context/AuthContext'
import { supabase } from '@/lib/supabase'
import { FEATURE_DEFINITIONS } from '@/lib/featureRegistry'

export default function AdminFeatureControls() {
  const { user } = useAuth()
  const [enabled, setEnabled] = useState<Record<string, boolean>>(() => Object.fromEntries(FEATURE_DEFINITIONS.map((feature) => [feature.id, feature.status !== 'planned'])))
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState<string | null>(null)
  useEffect(() => { supabase.rpc('admin_get_settings', { p_admin_id: user?.uid, p_prefix: 'feature_' }).then(({ data }) => { const next = Object.fromEntries(FEATURE_DEFINITIONS.map((feature) => [feature.id, feature.status !== 'planned'])) as Record<string, boolean>; for (const row of data ?? []) { const id = row.setting_key.replace(/^feature_/, '').replace(/_enabled$/, ''); const value = typeof row.setting_value === 'string' ? row.setting_value : row.setting_value?.value; if (id in next && typeof value === 'string') next[id] = value === 'true' } setEnabled(next); setLoading(false) }) }, [user?.uid])
  const groups = useMemo(() => FEATURE_DEFINITIONS.reduce<Record<string, typeof FEATURE_DEFINITIONS>>((acc, feature) => { (acc[feature.category] ??= []).push(feature); return acc }, {}), [])
  const save = async () => { setSaving(true); setMessage(null); for (const feature of FEATURE_DEFINITIONS) { const { error } = await supabase.rpc('admin_upsert_setting', { p_admin_id: user?.uid, p_key: `feature_${feature.id}_enabled`, p_value: { value: String(enabled[feature.id]) } }); if (error) { setMessage('Feature control সেভ করা যায়নি। Admin migration প্রয়োগ হয়েছে কি না দেখুন।'); setSaving(false); return } } setSaving(false); setMessage('Feature control সেভ হয়েছে।') }
  const activeCount = Object.values(enabled).filter(Boolean).length
  return <AdminShell><AdminPageHeader title="Feature Control Center" description={`${FEATURE_DEFINITIONS.length}টি marketplace feature-এর status ও visibility এক জায়গা থেকে নিয়ন্ত্রণ করুন।`} actions={<button onClick={save} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#0e6bdc] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Save size={16} />{saving ? 'সেভ হচ্ছে...' : 'সব পরিবর্তন সেভ করুন'}</button>} /><div className="mb-5 flex items-center gap-2 rounded-2xl bg-brand-50 p-4 text-sm text-brand-800"><Check size={18} />{activeCount}/{FEATURE_DEFINITIONS.length}টি feature enabled · Planned feature আগে implement করে তারপর চালু করুন।</div>{message && <p className="mb-5 rounded-xl bg-brand-50 p-4 text-sm text-brand-700">{message}</p>}{loading ? <AdminTableCard><p className="p-10 text-center text-sm text-slate-500">Feature controls লোড হচ্ছে...</p></AdminTableCard> : <div className="space-y-5">{Object.entries(groups).map(([category, features]) => <AdminTableCard key={category}><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold text-slate-900">{category}</h2></div><div className="grid gap-2 p-4 sm:grid-cols-2">{features.map((feature) => <label key={feature.id} className={`flex cursor-pointer items-start gap-3 rounded-xl border p-3 ${enabled[feature.id] ? 'border-brand-200 bg-brand-50/40' : 'border-slate-200 bg-white'}`}><input type="checkbox" checked={Boolean(enabled[feature.id])} onChange={(e) => setEnabled((current) => ({ ...current, [feature.id]: e.target.checked }))} className="mt-1 h-4 w-4 accent-[#017c50]" /><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-slate-800">{feature.label}</span><span className="mt-1 flex items-center gap-1 text-[11px] text-slate-400"><CircleHelp size={12} />{feature.id} · {feature.status}</span></span></label>)}</div></AdminTableCard>)}</div>}</AdminShell>
}
